### ISSUE TITLE
Update container config

### ISSUE THREAD

**Issue by MiguelRodo** [MiguelRodo/Test23MusvosviRToFlowJo#2]
Hi Munya, I updated the config files (largely in `.devcontainer/`), as I think that sometimes an error can crop up if certain `R` packages installed by default are not sufficiently up to date. So, to grab the updates, run the following in the shell (not `R`, just the "default" terminal):

`.devcontainer/scripts/update.sh && .devcontainer/scripts/post-create-command-r.sh`

**Comment by MunyaMusvosvi** [comment]
Hi @MiguelRodo,

I am having difficulty with the analysis in codespaces. R terminates when I run gt_gating(gating_strategy, temp_ncfs). I am not sure why this is. When I start the codespace, I type radian then renv::restore(). Can you see if you could try running the R script titled (Cortis_kids_script_to_get_openCyto_wsp_files) and if you get the same issue?

It looks like it is something associated to typing radian in bash vs typing radian in python. The panel on the left is linked to the python3 and the one on the right is linked to the bash

<img width="792" alt="image" src="https://github.com/SATVILab/Template23MusvosviGatingSetToWsp/assets/99468900/9d0fb0b3-6305-4081-b031-af4afd70e2fe">

**Comment by MunyaMusvosvi** [comment]
> Hi @MiguelRodo,
> 
> I am having difficulty with the analysis in codespaces. R terminates when I run gt_gating(gating_strategy, temp_ncfs). I am not sure why this is. When I start the codespace, I type radian then renv::restore(). Can you see if you could try running the R script titled (Cortis_kids_script_to_get_openCyto_wsp_files) and if you get the same issue?

**Comment by MunyaMusvosvi** [comment]
Nevermind, it looks like I have it working now, but it looks like codespaces does not like my loop because it seems to terminate when I run the loop, but if I run each set of .fcs files independently it runs ok. Do you think using a more powerful machine would help?

**Comment by MiguelRodo** [comment]
Have you shared the latest version of your code? If so, then I can have a look exactly.

You could also just try upgrading your machine, and then reverting if it doesn't seem to fix it. RAM might be an issue, but I kind of doubt it seeing as you're not running more than 4GB of files (I think) and the RAM is 8GB. But worth looking at

**Comment by MunyaMusvosvi** [comment]
When you say share the latest version of my code do you mean to click the "publish branch"? I have tried to upgrade my machine, but that did not fix the issue. I think since I am managing to run the sets of files one by one and I don't have a lot, we could troubleshoot next year. It's not urgent.

**Comment by MiguelRodo** [comment]
Well, I'd run `git push` on the command line and see what happens (not in R, just the shell). Otherwise click publish branch

If you do that, I can have a look. I won't take long, but at least we can see how much this approach helps debugging and collaborating

**Comment by MunyaMusvosvi** [comment]
I just tried git push and also publish branch and I got the following errors. I am happy to jump on a Teams call if it will be more efficient.

<img width="1728" alt="image" src="https://github.com/SATVILab/Template23MusvosviGatingSetToWsp/assets/99468900/7e4d8ba4-b918-4847-b6a8-d1dba2b2c887">

**Comment by MiguelRodo** [comment]
Okay, I see. So, one problem is that your project is a Git repository, but that it's not linked with the GitHub remote (i.e. `SATVILab/Template23MusvosviGatingSet`). Another problem may be that you do not have the right Git password (`PAT`) to link to `SATVILab/Template23MusvosviGatingSet`). 

To find out, run the following:

```bash
if [ -n "$GITHUB_TOKEN" ]; then
  pushd /tmp
  git clone https://"${GITHUB_TOKEN}"@github.com/SATVILab/Template23MusvosviGatingSet.git && echo "success" || echo "failure"
  popd
else
  echo "GITHUB_TOKEN env var not set"
fi
```

Just copy and paste the above into the command line (not the `R` terminal). Then let me know what it says

**Comment by MiguelRodo** [comment]
Im in the Pinelands library, so can't really do teams rn. But the above will help.

I'm not entirely sure why you were not automatically linked. I normally am. Perhaps it's because I created the GitHub repo. Will need to figure that out

**Comment by MiguelRodo** [comment]
Oh, wait - did you create the codespace based on my account? If so, that would be why, I would think

**Comment by MunyaMusvosvi** [comment]
I am not sure what happened, but I think it is more than that. I just noticed that it looks like my Repo is in the wrong place. 
MunyaMusvosvi/Template23MusvosviGatingSet. I must have made a copy early on. I have sent you an invite

**Comment by MiguelRodo** [comment]
Well, it's fine to keep the repo in your personal github page. SATVI just doesn't pay for codespace usage there (and you have free hours, I think 60 a month on the 2-core machine).

I've accepted the invite, and started letting the codespace create itself
